name: Piesek
on: 
  label:
    types:
      - created
  push:
    branches:
      - master   

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Every time
      run: echo "This step will always run"
